# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CSl_FS7NFqlPK8VN-IaVsCJRXtp3DfRo
"""

print("Hello world!")

print("Estou aprendendo Python")

"Estou aprendendo python"

